
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WS
 */
public class FRMCASHIER extends javax.swing.JFrame {

    /**
     * Creates new form FRMCASHIER
     */
    public FRMCASHIER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lblTotalDue = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtless = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lbltota12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();
        lblCheckout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("CODE:");

        txtCode.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodeFocusLost(evt);
            }
        });
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("NAME:");

        lblName.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("PRICE:");

        lblPrice.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Quantity:");

        txtQuantity.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Total:");

        lblTotal.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(255, 255, 153));
        btnAdd.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnAdd.setText("Add to Cart");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblCart.setBackground(new java.awt.Color(0, 204, 255));
        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCart);

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel8.setText("Total Order Due:");

        lblTotalDue.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblTotalDue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalDue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        lblTotalDue.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel9.setText("Less");

        txtless.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        txtless.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlessFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlessFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel11.setText("Cash");

        txtCash.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        txtCash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCashFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCashFocusLost(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel12.setText("Tot.");

        lbltota12.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lbltota12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lbltota12FocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel10.setText("Change");

        lblChange.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N

        lblCheckout.setBackground(new java.awt.Color(153, 255, 153));
        lblCheckout.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblCheckout.setText("CHECK OUT");
        lblCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCheckoutActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ADD PRODUCT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtCode))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQuantity)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalDue, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtless, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(txtCash)
                                .addComponent(lbltota12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCheckout)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(jLabel8))
                    .addComponent(lblTotalDue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtless, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lbltota12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodeFocusLost
      String code = txtCode.getText().trim();
    String filePath = "C:\\Users\\WS\\Documents\\NetBeansProjects\\BERKABZ\\your_file_name.csv"; // Update with your file name and extension

    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
        String line;
        boolean found = false;

        while ((line = br.readLine()) != null) {
            String[] parts = line.split(","); // Assuming CSV format; adjust split based on your file format

            // Check if the code matches the data in the file
            if (parts.length >= 4 && parts[0].trim().equals(code)) {
                lblName.setText(parts[1].trim()); // Assuming name is in the second column
                lblPrice.setText(parts[2].trim()); // Assuming price is in the third column
                // Populate other fields similarly using appropriate column indices

                found = true;
                break;
            }
        }

        if (!found) {
            txtCode.setBackground(Color.pink);
            JOptionPane.showMessageDialog(this, "NO PRODUCT FOUND!", "INVALID", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (IOException e) {
        e.printStackTrace(); // Handle file reading errors appropriately
    }

    }//GEN-LAST:event_txtCodeFocusLost

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        // TODO add your handling code here:
        String x = txtQuantity.getText().trim();
        if(x.isEmpty()){
            txtQuantity.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "You need to input a quantity!","Invalid Quanitity",JOptionPane.ERROR_MESSAGE);
            txtQuantity.setBackground(Color.white);
            txtQuantity.setText("");
        }else {
            int quantity = Integer.parseInt(x);
            if(quantity > quantity){
                txtQuantity.setBackground(Color.red);
                JOptionPane.showMessageDialog(this, "Remaining Stock " + quantity,"Invalid Quanitity",JOptionPane.ERROR_MESSAGE);
                txtQuantity.setBackground(Color.white);
                txtQuantity.setText(Integer.toString(quantity));
                // txtQuantity.requestFocus();
            }else{
                float total = quantity * (float)quantity;
                lblTotal.setText(Float.toString(total));
            }
        }

    }//GEN-LAST:event_txtQuantityFocusLost

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    


    }//GEN-LAST:event_btnAddActionPerformed

    private void txtlessFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlessFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlessFocusGained

    private void txtlessFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlessFocusLost
        // TODO add your handling code here:
         try {
        float total_fit = Float.parseFloat(lblTotalDue.getText());
        float less_fit = Float.parseFloat(txtless.getText());

        double total = total_fit * less_fit;
        double a = total_fit - total;
        lbltota12.setText(Double.toString(a)); // Update the label with the calculated value
        txtless.setBackground(Color.green);
    } catch (Exception e) {
        System.out.println(e);
        txtless.setText(""); // Clear txtless if an exception occurs
    }
    }//GEN-LAST:event_txtlessFocusLost

    private void txtCashFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashFocusGained
        // TODO add your handling code here:
        txtCash.setBackground(new Color(152, 203, 254));
        txtCash.setForeground(Color.yellow);
        txtCash.setText("");

    }//GEN-LAST:event_txtCashFocusGained

    private void txtCashFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashFocusLost
        // TODO add your handling code here:
        txtCash.setBackground(Color.yellow);
        txtCode.setForeground(Color.orange);
        String total = lblTotal.getText();
        String amount = txtCash.getText();
        if (amount.length()> 0){
            float total_flt = Float.parseFloat(total);
            float amount_flt =Float.parseFloat(amount);
            if(amount_flt < total_flt){
                JOptionPane.showMessageDialog(this, "Not enough money!");
            }else{
                float change_flt = amount_flt - total_flt;
                String change = Float.toString(change_flt);
                lblChange.setText(change);
                if (!txtCash.getText().equals("")) {
                    lblCheckout.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_txtCashFocusLost

    private void lbltota12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbltota12FocusLost
        // TODO add your handling code here:
        double a = Double.parseDouble(lblTotalDue.getText());
        double b = Double.parseDouble(txtless.getText());
        double totals = a-b;
        lbltota12.setBackground(Color.green);
    }//GEN-LAST:event_lbltota12FocusLost

    private void lblCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCheckoutActionPerformed
        // TODO add your handling code here:
        String code = txtCode.getText();
    String name = lblName.getText();
    String price = lblPrice.getText();
    String cash = txtCash.getText();
    String quantity = txtQuantity.getText();
    String total = lblTotalDue.getText();
    String change = lblChange.getText();

    int result = JOptionPane.showConfirmDialog(null, "Are you sure?", "", JOptionPane.YES_NO_OPTION);
    if (result == JOptionPane.YES_OPTION) {
        // Processing logic after confirmation without database operations
        // For instance:
        // Assuming you want to save the data to a local file
        String filePath = "C:\\Users\\WS\\Documents\\NetBeansProjects\\BERKABZ\\your_file_name.csv";

        // Create or append to a file with the collected data
        try (PrintWriter writer = new PrintWriter(new FileWriter(filePath, true))) {
            // Write the data in CSV format to the file
            writer.println(code + "," + name + "," + price + "," + quantity + "," + total + "," + cash + "," + change);
            JOptionPane.showMessageDialog(null, "Data saved to file", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

            // Clearing the fields after saving data to the file
            lblName.setText("");
            lblPrice.setText("");
            txtQuantity.setText("");
            lblTotal.setText("");
            txtCode.setText("");
            lblChange.setText("");
            txtCash.setText("");

            System.exit(0); // Closing the application

        } catch (IOException e) {
            System.out.println("Error writing to file: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_lblCheckoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FRMCASHIER mf = new FRMCASHIER();
        mf.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMCASHIER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMCASHIER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMCASHIER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMCASHIER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMCASHIER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChange;
    private javax.swing.JButton lblCheckout;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalDue;
    private javax.swing.JLabel lbltota12;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtless;
    // End of variables declaration//GEN-END:variables
}
